config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'movies#index'
  get '/movies/top-rated', to: 'movies#topRated' 
  get '/auth/google_oauth2/callback', to: 'sessions#google_login'
  resources :movies, only: [:index, :show]
  resources :tickets, only: [:index, :show, :new, :create]

  resources :movies, only: [:show] do 
    resources :tickets, only: [:new, :show]
  end

  resources :users, only: [:show] do
    resources :tickets, only: [:index]
  end

  get '/profile', to: 'users#index', as: 'profile'
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :tickets
    has_many :users, through: :tickets
    validates_presence_of :name, :rated


    scope(:top_rated, -> {order(rated: :desc )})
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
    belongs_to :movie
    validates_presence_of :quantity
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tickets
    has_many :movies, through: :tickets
    validates_uniqueness_of :username, :case_sensitive => false 
    validates_presence_of :username
    has_secure_password
end

def find_movie_id(movie_id)
    user = current_user 
    tickets = user.tickets
    tickets.where(:movie_id => movie_id).limit(1)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method(:logged_in?, :current_username)
    def current_username
        @current_user = User.find_by(id: session[:user_id])
        @current_user.username
      end

    def current_user
        @current_user = User.find_by(id: session[:user_id])
    end

    def redirect_if_not_logged_in
        if !logged_in?
            redirect_to login_path
        end
    end

    def set_movie_id
       @movie =  Movie.find_by(id: params[:movie_id])
    end

    def set_movie
        @movie =  Movie.find_by(id: params[:id])
    end

    def logged_in?
        if session[:user_id]
            return true
        else
            return false
        end
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
        @movies = Movie.all
    end

    def topRated
        @movies = Movie.top_rated
        render "index"
    end

    def show
        set_movie
    end

    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.new(movie_params)
        if @movie.save
            redirect_to movie_path(@movie)
        else
            render "new"
        end
    end

    def edit
        set_movie
    end

    def update
        set_movie
        @movie.update(movie_params)
        redirect_to movie_path(@movie)
    end

    def destroy
        set_movie
        @movie.delete
        redirect_to movies_path
    end




    private 

    def movie_params
        params.require(:movie).permit(:name, :rated)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @errors = []
    end

    def create
        @user = User.find_by(username: params[:user][:username])


        if @user && @user.authenticate(params[:user][:password])
            
            session[:user_id] = @user.id
            flash[:messages] = "Successfully Logged in"
            redirect_to movies_path
        elsif @user
            @errors = ["Invalid Password"]
            render "new"
        else
            @errors = ["Invalid Username"]
            render "new"
        end
    end

    def google_login
        user = User.find_or_create_by(username: g_auth['email']) do |u|
            u.password = SecureRandom.hex(5)
        end
        if user.save
            flash[:message] = "Login Successful!"
            session[:user_id] = user.id
            redirect_to movies_path
        else
            flash[:message] = "Login Failed via google"
            redirect_to signup_path
        end
    end


    def destroy
        session.clear
        redirect_to movies_path
    end


    private 
    
    def g_auth
        self.request.env['omniauth.auth']['info']
    end
end

app/controllers/tickets.rb
class TicketsController < ApplicationController
    def new
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

    before_action(:redirect_if_not_logged_in)

    def index 
        @user = User.find_by(id: params[:user_id])
    end

    def new
        if params[:movie_id]
            @collection = false
            set_movie_id
            @ticket = @movie.tickets.build
            @movies = Movie.all
        else
            @collection = true
            @ticket = Ticket.new
            @movies = Movie.all
        end
    end

    def create
        @movie = Movie.find_by(id: params[:ticket][:movie_id])
        @ticket = Ticket.new(ticket_params)
        movie_id = find_movie_id(@ticket.movie_id)
        if movie_id.blank?
            @ticket.user_id = session[:user_id]
            @ticket.name = @movie.name
            if @ticket.save
                flash[:message] = "Tickets Purchased!"
                session[:ticket_quantity] = @ticket.quantity
                redirect_to movie_ticket_path(@movie.id, @ticket.id)
            else
                render 'new'
            end
        else
            @ticket.user_id = session[:user_id]
            if @ticket.valid?
                new_quantity = movie_id[0].quantity += @ticket.quantity
                movie_id[0].update(movie_id: movie_id[0].movie_id, quantity: new_quantity)
                flash[:message] = "Tickets Purchased!"
                session[:ticket_quantity] = @ticket.quantity
                redirect_to movie_ticket_path(movie_id[0].movie_id, @ticket.movie_id)
            else
                render 'new'
            end
        end
    end

    def show
        set_movie_id
        @quantity = session[:ticket_quantity]
        session[:ticket_quantity] = nil
        @ticket = Ticket.find_by(id: params[:id])
    end



    private

    def ticket_params
        params.require(:ticket).permit(:movie_id, :quantity)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :redirect_if_not_logged_in, only: [:index]
    def new 
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to movies_path
        else
            @errors = @user.errors.full_messages
            render 'new'
        end
    end

    def index
        @user = current_user
    end











    private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.erb
<% errors && errors.each do |e| %>
    <li><%=e%></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuickFilm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  </head>
  

  <% if logged_in? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Quick Film</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/profile">Profile <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="/movies">Movies</a>
            <a class="nav-item nav-link" href="/tickets/new">Buy Tickets</a>
            <a class="nav-item nav-link" href="/logout">Logout</a>
          </div>
        </div>
      </nav>
    <% else %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Quick Film</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="/signup">Sign Up Here <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="/login">Login Here</a>
      </div>
    </div>
  </nav>
    <% end %>



  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%=form_for(@movie) do |f|%>
    <%=f.label("Movie Name:") %>
    <%=f.text_field(:name) %>
    <%=f.label("Movie Rating:") %>
    <%=f.text_field(:rated) %>
    <%=f.submit "Submit"%>
<%end%>

app/views/movies/edit.html.erb
<%= render partial: "application/errors", locals: {errors: @movie.errors.full_messages} %>


<%= render('form') %>

app/views/movies/index.html.erb
<h1>List of Movies you can buy tickets for</h1>

<% if @rated_movies == nil %>
    <%= button_to "Filter by rating", movies_top_rated_path, method: "get" %>
    <br>
    <% @movies.each do |movie| %>
        <li><%= link_to movie.name, movie_path(movie) %> - <%= movie.rated %>
    <% end %>

<% elsif @movies == nil %>
    <%= button_to "Filter By latest", movies_path, method: "get" %>
    <br>
    <% @rated_movies.each do |movie| %>
        <li><%= link_to movie.name, movie_path(movie) %> - <%= movie.rated %>
    <% end %>
<% end %>

app/views/movies/new.html.erb
<%= render partial: "application/errors", locals: {errors: @movie.errors.full_messages} %>


<%= render('form') %>

app/views/movies/show.html.erb
<h1><%= @movie.name %></h1>
<h2><%= @movie.rated %></h2>
<br>



<%= link_to "Buy Tickets For This Movie", new_movie_ticket_path(@movie.id) %>

app/views/tickets/index.html.erb
<h3>Here's a list of movies you've purchased tickets for:</h3>

<% @user.tickets.each do |ticket| %>
    <li> <%= ticket.name %> | <%= ticket.quantity %> tickets purchased </li> 
<% end %>

app/views/tickets/new.html.erb
<h1>Buy Tickets</h1>

<%= render partial: "application/errors", locals: {errors: @ticket.errors.full_messages} %>

<% if @movie %>
    <h3>Buy tickets for <%= @movie.name %> </h3>
<% end %>


    <%= form_for @ticket do |f| %>
        <% if @collection %>
            <%= f.label("Select Movie to buy tickets for:") %>
            <br>
            <%= f.collection_select(:movie_id, @movies, :id, :name) %>
            <br>
            <br>
        <% else %>
            <%= f.hidden_field :movie_id, value: @movie.id %>
        <% end %>
        <%= f.label("Quantity: ") %>
        <%= f.number_field(:quantity) %>
        <%= f.submit("Buy Tickets") %>
    <% end %>

app/views/tickets/show.html.erb
<h1> Thank you,  for purchasing <%= @quantity %> tickets for <%= @ticket.name %> ! </h1>

app/views/users/index.html.erb
<h1>User Profile for <%= current_username %></h1>
<h3>Here's a list of movies you've purchased tickets for:</h3>

<% @user.tickets.each do |ticket| %>
    <li> <%= ticket.name %> | <%= ticket.quantity %> tickets purchased </li> 
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

  <% @errors && @errors.each do |e| %>
    <li><%=e%></li>
  <%end%>
<%= form_for @user, url: signup_path do |f| %>
  <%=f.label "Username"%>
  <%=f.text_field :username%>
  <%=f.label "Password"%>
  <%=f.password_field :password %>
  <%=f.label "Password Confirmation"%>
  <%=f.password_field :password_confirmation %>
  <%=f.submit "Sign Up"%>
<%end%>